name: ci

on: # Rebuild any PRs and main branch changes
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:

    - name: Prepare Xcode
      uses: maxim-lobanov/setup-xcode@v1 # https://github.com/marketplace/actions/setup-xcode-version
      with:
        xcode-version: latest-stable

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and Test VSM
      uses: sersoft-gmbh/xcodebuild-action@v2 # https://github.com/marketplace/actions/xcodebuild-action
      with:
        spm-package: ./
        scheme: VSM
        destination: platform=iOS Simulator,OS=15.2,name=iPhone 13
        action: test
    
    - name: Build and Test Demo App
      uses: sersoft-gmbh/xcodebuild-action@v2 # https://github.com/marketplace/actions/xcodebuild-action
      with:
        project: ./Demos/Shopping/Shopping.xcodeproj
        scheme: Shopping
        destination: platform=iOS Simulator,OS=15.2,name=iPhone 13
        action: test
