name: ci

on: # Rebuild any PRs and main branch changes
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build-and-test-vsm:
    runs-on: macos-12
    steps:
      - name: Prepare Xcode
        uses: maxim-lobanov/setup-xcode@v1 # https://github.com/marketplace/actions/setup-xcode-version
        with:
          xcode-version: 14.2

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and Test VSM
        uses: sersoft-gmbh/xcodebuild-action@v2 # https://github.com/marketplace/actions/xcodebuild-action
        with:
          spm-package: ./
          scheme: VSM
          destination: platform=iOS Simulator,OS=latest,name=iPhone 14
          action: test
  
  shopping-swiftui-test:
    runs-on: macos-12
    steps:
      - name: Prepare Xcode
        uses: maxim-lobanov/setup-xcode@v1 # https://github.com/marketplace/actions/setup-xcode-version
        with:
          xcode-version: 14.2

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and Test Demo App
        uses: sersoft-gmbh/xcodebuild-action@v2 # https://github.com/marketplace/actions/xcodebuild-action
        with:
          project: ./Demos/Shopping/Shopping.xcodeproj
          scheme: Shopping
          destination: platform=iOS Simulator,OS=latest,name=iPhone 14
          action: test

  shopping-uikit-test:
    runs-on: macos-12
    steps:
      - name: Prepare Xcode
        uses: maxim-lobanov/setup-xcode@v1 # https://github.com/marketplace/actions/setup-xcode-version
        with:
          xcode-version: 14.2

      - name: Checkout
        uses: actions/checkout@v3

      - name: (UIKit) Build and Test Demo App
        uses: sersoft-gmbh/xcodebuild-action@v2 # https://github.com/marketplace/actions/xcodebuild-action
        with:
          project: ./Demos/Shopping/Shopping.xcodeproj
          scheme: Shopping - UIKit
          destination: platform=iOS Simulator,OS=latest,name=iPhone 14
          action: test
