name: ci

on: # Rebuild any PRs and main branch changes
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-vsm:
    runs-on: macos-13
    steps:
      - name: Prepare Xcode
        uses: maxim-lobanov/setup-xcode@v1 # https://github.com/marketplace/actions/setup-xcode-version
        with:
          xcode-version: 15.0.1

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and Test VSM on macOS
        uses: sersoft-gmbh/xcodebuild-action@v2 # https://github.com/marketplace/actions/xcodebuild-action
        with:
          spm-package: ./
          scheme: VSM
          destination: platform=macOS
          action: test
      
      - name: Build and Test VSM on iOS
        uses: sersoft-gmbh/xcodebuild-action@v2 # https://github.com/marketplace/actions/xcodebuild-action
        with:
          spm-package: ./
          scheme: VSM
          destination: platform=iOS Simulator,OS=latest
          action: test
      
      - name: Build and Test VSM on watchOS
        uses: sersoft-gmbh/xcodebuild-action@v2 # https://github.com/marketplace/actions/xcodebuild-action
        with:
          spm-package: ./
          scheme: VSM
          destination: platform=watchOS Simulator,OS=latest
          action: test

      - name: Build and Test VSM on tvOS
        uses: sersoft-gmbh/xcodebuild-action@v2 # https://github.com/marketplace/actions/xcodebuild-action
        with:
          spm-package: ./
          scheme: VSM
          destination: platform=tvOS Simulator,OS=latest
          action: test

  
  test-swiftui-demo-app:
    runs-on: macos-13
    steps:
      - name: Prepare Xcode
        uses: maxim-lobanov/setup-xcode@v1 # https://github.com/marketplace/actions/setup-xcode-version
        with:
          xcode-version: 15.0.1

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and Test Demo App
        uses: sersoft-gmbh/xcodebuild-action@v2 # https://github.com/marketplace/actions/xcodebuild-action
        with:
          project: ./Demos/Shopping/Shopping.xcodeproj
          scheme: Shopping
          destination: platform=iOS Simulator,OS=latest
          action: test

  test-uikit-demo-app:
    runs-on: macos-13
    steps:
      - name: Prepare Xcode
        uses: maxim-lobanov/setup-xcode@v1 # https://github.com/marketplace/actions/setup-xcode-version
        with:
          xcode-version: 15.0.1

      - name: Checkout
        uses: actions/checkout@v3

      - name: (UIKit) Build and Test Demo App
        uses: sersoft-gmbh/xcodebuild-action@v2 # https://github.com/marketplace/actions/xcodebuild-action
        with:
          project: ./Demos/Shopping/Shopping.xcodeproj
          scheme: Shopping - UIKit
          destination: platform=iOS Simulator,OS=latest
          action: test
