name: CI

on: # Rebuild any PRs and main branch changes
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:

    - name: Prepare Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and Test VSM
      working-directory: ./
      run: xcodebuild test -scheme VSM -destination 'platform=iOS Simulator,OS=15.6,name=iPhone 13' | xcpretty && exit ${PIPESTATUS[0]}
    
    - name: Build and Test Demo App
      working-directory: ./Demos/Shopping
      run: xcodebuild test -scheme Shopping -project Shopping.xcodeproj -destination 'platform=iOS Simulator,OS=15.6,name=iPhone 13' | xcpretty && exit ${PIPESTATUS[0]}
